openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0.1
servers:
  - url: 'https'
paths:

components:
  schemas:

    ServiceModel:
      required:
        - id
        - model
        - items
      type: object
      properties:
        id:
          type: integer
          format: int32
        model:
          $ref: '#/components/schemas/Model'
        items:
          type: array
          items:
            $ref: '#/components/schemas/ModelItem'
